### ISSUE TITLE
Doesn't record when number withheld 

### ISSUE THREAD

**Issue by Derkish** [chenxiaolong/BCR#111]
If the recipient withholds their phone number (also known as private number), the app won't record the incoming phone call. Apart from that, your app is perfect.

I'm unsure about other countries, but in Britain you can test this (withhold your phone number) by prefixing 141 before the dialing mobile number that bcr is installed on.

**Comment by chenxiaolong** [comment]
Hmm, I'm not sure how to test this in the US. I don't think we have anything like the 141 prefix you mentioned (which seems pretty neat).

Could you enable debug mode (long press the version number in BCR) and then attempt to record a call from a private number? It should hopefully create a log file in the output folder. If not (because the recording isn't getting triggered), you may have to attempt to record 2 calls for it to create the log file: first from a private number and the second from a non-private number.

**Comment by effectively0** [comment]
I'm fairly sure you can do a similar thing in the USA. It's just CallerID https://smallbusiness.chron.com/edit-caller-id-android-28530.html

**Comment by Derkish** [comment]
I uninstalled bcr due to it not recording incoming numbers when caller ID is withheld  (I'm now using another app which isn't free but fits my needs), but apart from that bug, your app is excellent.

Yeah effectively0 is right, that looks the equivalent thing in America.
https://www.geeky-gadgets.com/how-to-hide-your-number-on-an-android-phone-30-06-2022/

According to the article, you can  also withhold number on Android phones by going, Phone > Settings > Calls >Additional Settings > Caller ID > Hide my number

So changing Caller ID to hidden and then phoning another phone with bcr installed is a way to test it.

**Comment by chenxiaolong** [comment]
Thanks! I was not aware the US had a prefix too (`*67`).

Looks like there's two issues:
* the method BCR uses to grab the phone number (for the filename) is crashing
* the crash doesn't get reported to the user so it looks like nothing is happening

I'll fix these and likely release a new version tonight.

**Comment by chenxiaolong** [comment]
This is fixed in #114 and will be part of version 1.17.

**Comment by chenxiaolong** [comment]
Version 1.17 has been released.
