### ISSUE TITLE
Audio problem

### ISSUE THREAD

**Issue by Block2Paz** [chenxiaolong/BCR#122]
When the call is recorded, my voice is heard very softly, while that of the interlocutor is very loud. What can I do?

**Comment by chenxiaolong** [comment]
BCR cannot tell the difference between your own audio and the interlocutor's audio because Android combines both of them into a single audio stream before it reaches BCR.

The low volume might be caused by poor mixer settings in your device's ROM. It may be possible to fix by editing `/vendor/etc/mixer_paths.xml`, but I'm not familiar with that, so I unfortunately don't have any suggestions.

**Comment by Block2Paz** [comment]
Okay thank you
