### ISSUE TITLE
[Feature] Uplink and downlink separated source

### ISSUE THREAD

**Issue by Ceynou** [chenxiaolong/BCR#124]
Hi thanks for the application, it's working very well, I don't know what you think about that but would that be convenient to have at least the caller's source(downlink?), a clean audio without my voice, the wind, the noise coming from my mic overlapping with the caller's audio.

**Comment by PatrykMis** [comment]
I'm afraid it it's out of scope of this project ("BASIC" Call Recorder)
Anyway it will be great optional feature - e.g. stereo wav recording, uplink on the left and downlink on right channel. Though I'm not sure if it's possible to record from both sources at once.

**Comment by chenxiaolong** [comment]
> Anyway it will be great optional feature - e.g. stereo wav recording, uplink on the left and downlink on right channel. Though I'm not sure if it's possible to record from both sources at once.

That's a great idea, so I tried implementing that. There are 3 call recording audio streams on Android:

* `VOICE_CALL` - both uplink and downlink merged into single mono audio stream by Android
* `VOICE_UPLINK` - mono audio stream for uplink
* `VOICE_DOWNLINK` - mono audio stream for downlink

BCR normally uses `VOICE_CALL`. I tried making it record from `VOICE_UPLINK` and `VOICE_DOWNLINK` at the same time into a stereo output file.

Unfortunately, the audio driver responsible for call recording does not support that. It's buggy and you always end up with 2 downlink audio streams instead of 1 uplink + 1 downlink. At least on the Google Pixel 6 Pro, the bug is in the proprietary `audio.primary.gs101.so` driver, so it's not possible for BCR to work around this.

**Comment by chenxiaolong** [comment]
Just for the heck of it, I tried simply recording the `VOICE_CALL` stream in stereo mode. Android just puts the same mono stream in both channels :(

![image](https://user-images.githubusercontent.com/646253/187047238-1c916b52-ae3d-43cc-8eda-3d1f8948b3a8.png)

**Comment by ericek111** [comment]
Getting the downlink channel is the better alternative, because we can just record uplink from the local microphone, if the user chooses so. Would that be possible?

**Comment by Ceynou** [comment]
Sorry but bump

**Comment by PatrykMis** [comment]
"bunping" is not helping anyone here, the issue is still marked opened for some reason.
You can experiment with the code which have been already made  by @chenxiaolong in [stereo branch](https://github.com/chenxiaolong/BCR/tree/stereo).

**Comment by Ceynou** [comment]
Ah, I see it closed, maybe I'm not looking at the right issue

**Comment by cgarz** [comment]
This is a killer feature that I've always dreamed of having.
Has anyone tested if the stereo branch works on a device that does not use the `audio.primary.gs101.so` driver?

I'm unable to find any such file on my Fairphone 3+ with `find / -iname '*gs101*'` from a root terminal.
@chenxiaolong  I'd be more than happy to test. Is there is an apk available?

**Comment by PatrykMis** [comment]
Unfortunately it seams to be impossible at all. If any of VOICE_CALL, VOICE_UPLINK or VOICE_DOWNLINK stream is beeing taken, the rest seams to be unavailable or in best scenario outputs silence.

**Comment by Ceynou** [comment]
> Unfortunately it seams to be impossible at all. If any of VOICE_CALL, VOICE_UPLINK or VOICE_DOWNLINK stream is beeing taken, the rest seams to be unavailable or in best scenario outputs silence.

How about downlink and mic separately then merged?

**Comment by PatrykMis** [comment]
Mic is silenced when any of those 3 is active.

**Comment by Ceynou** [comment]
> Mic is silenced if any of those 3 is active, at least in Android 13, but I have to test it more extensively. I would like to have this feature, too.

That's unfortunate, at least for non rooted device if we can ever bypass it in root

**Comment by chenxiaolong** [comment]
With #772, which will be included in version 2.0, BCR can now optionally record in stereo for devices that support it. The uplink is recorded to the left channel and the downlink to the right channel. Currently, only newer Google Pixel devices are known to support this.

**Comment by cgarz** [comment]
Fantastic news! I was so excited I tested immediately. 😆 

Unfortunately incoming audio is silent with stereo. 😩

I'm on a Fairphone 3 running LineageOS 22 (22.2-20260107-NIGHTLY-FP3).

Is there something I can do to get it working since I'm on a custom rom with root? Another magisk module or something to add the required driver?

**Comment by chenxiaolong** [comment]
Sadly not, this is something that requires support from the OEM. Maybe the community could do it if the audio HAL was open source for your device.

Google explicitly added support for this on the Pixel devices recently, in order to support their new AI features in Google Dialer. They used to have the same limitation where recording the uplink and downlink separately didn't work.

**Comment by cgarz** [comment]
Awww typical Ghoulgle 😩.
Only when it benifits their AI slop do they accidentally allow their users a tiny shred of freedom 😒.
I wish they would just crash and burn. They are blocking proper real Linux phones from becoming viable.

Thanks for adding the feature anyway 👍
