### ISSUE TITLE
Is it possible to make menu of calls history for better organizing?

### ISSUE THREAD

**Issue by GAnimator** [chenxiaolong/BCR#135]
Your app is awesome, works perfectly but the lack of menu of calls/contacts history the only issue that makes this app much inconvenient than others. Is it possible to wait for that feature in next updates?

**Comment by GAnimator** [comment]
That will definitely make your app best of android 9+ call recorders

**Comment by J4CKED** [comment]
All the recording apps I know have a mass of options, have a list of recorded calls, require multiple permissions, unfortunately most can't record calls from Android 10 or 11.
BCR is minimal and works, it's a huge advantage and it's the best.

**Comment by greatcoder88** [comment]
This module is best, i think it is better to keep it this way because it is minimal and works flawlessly.

**Comment by nicorac** [comment]
I do agree that this app is the best one available nowadays, and it works without any issue but... 😂 a very minimal and simple list of recordings would be appreciated.

It'll be useful to keep the recordings folder clean in an easy way, no need to use a file manager.
Well, also being able to play recordings straight from the list will be a plus 🙄

**Comment by Derkish** [comment]
I also believe that a minimal approach is better because call history is already in the phone app. The problem being is that if you have a list of calls in bcr, what naturally comes next is the ability to play these recordings from that list, which adds complexity if the user has already deleted the file behind the scenes etc.

**Comment by guysoft** [comment]
Suggestion If BCR outputs some kind of database/json file, a "call logs viewer" app could be built separately

**Comment by chenxiaolong** [comment]
At this point, I'm going to close this issue because it's unlikely I'll ever implement it, in the spirit of keeping the code as simple as possible.

I might add a shortcut within BCR to directly open a file manager to the output directory, but I won't be adding a recording list to BCR itself.

> Suggestion If BCR outputs some kind of database/json file, a "call logs viewer" app could be built separately

I like this idea and it's simple to implement, so I've opened #380 for this. It'd be useful for other use cases too.

**Comment by chenxiaolong** [comment]
In the next version of BCR, if you long press the output directory, BCR will open it in the system file manager (#383). Hopefully this makes it at least a little bit easier to access the recordings :slightly_smiling_face:

**Comment by nicorac** [comment]
> Suggestion If BCR outputs some kind of database/json file, a "call logs viewer" app could be built separately

Here you are: [BCR-GUI](https://github.com/nicorac/bcr-gui) 
(disclaimer: I'm the author of that app 😉)
