### ISSUE TITLE
Android/data not accessible with A13

### ISSUE THREAD

**Issue by laltroweb** [chenxiaolong/BCR#156]
Like from object, I can't access anymore to Android/data cause more restrictive system.
Can u switch to Android/media folder for audio files?
So, from this:
*/Android/data/com.chiller3.bcr/files
To this:
*/Android/media/com.chiller3.bcr/files

Hope u can fix 😅👍

Edit: ok, move by myself (entire com.* folder) and still work as expected (and swift backup can still backup without problems) 😎👍

**Comment by chenxiaolong** [comment]
By default, it uses `Android/data/<app ID>` for privacy because it's the only directory BCR can write to with no permissions and so 3rd party apps won't be able to scan/access/upload the recordings.

However, from BCR, you can change the output directory and pick anything you like. It can be any folder on the internal storage or an SD card.

**Comment by laltroweb** [comment]
Yep, indeed, as my previou edit, I move entire folder from data to media, all work as expected and I can backup this folder thanks to SwifthBackup.
![Screenshot_20221026-183353_Swift Backup](https://user-images.githubusercontent.com/16841896/198083336-23ad14a3-5794-4261-9796-d9cb2d43becd.png)
