### ISSUE TITLE
Possible to enable or disable call recording in the middle of a call?

### ISSUE THREAD

**Issue by bagarwa** [chenxiaolong/BCR#198]
I see that currently I'm not able to change the state of call recording after answering a phone call. If the call recording was enabled before I got the call, the call will be recorded and I can't stop it during the call. And if the call recording was not enabled before I got the call, I can't enable it during the call.

This leads to situations where I either keep it enabled all the time, and record unnecessary calls too and then delete the recording afterwards. OR not keep it enabled all the time, and risk missing to record a call that I should've, as I can't always make an excuse to the caller to call me again in a minute (giving me a chance to enable recording.)

It would be really really helpful if we can select whether to record a call or not, during the call itself.

(Pixel 7 Pro, Android 13, Magisk Canary.)

**Comment by chenxiaolong** [comment]
Would adding a delete option to the `Call recording in progress` notification be good enough for your use case? It would cancel the current recording and delete what has been recorded during the call so far.

That is the simplest thing for me to implement and I'd be willing to add that.

**Comment by bagarwa** [comment]
> Would adding a delete option to the `Call recording in progress` notification be good enough for your use case? It would cancel the current recording and delete what has been recorded during the call so far.

That would help in some scenarios where I know I would absolutely not need to record this call. Spam calls for example. 

But if in other calls which are not worth "_I should record this_" right now, and I press that delete button, but afterwards it turns important and I need to record that call, I no longer can.

I was originally thinking that enabling BCR will only enable BCR's `Call in progress` notification at the start of every call. That notification can have a "start recording" button. Tapping that button will actually start recording the call. 

But if it is too complicated to implement, would it be possible to add a "pause" option instead? For example, consider this scenario - 

- Call Recording is enabled. 
- User picks up an incoming call. BCR starts recording the call. 
- Conversation is not important, so user presses the "pause" button on the `Call recording in progress` notification. 
- Notification text changes to `Call recording is paused`, and the pause button text changes to "Resume".
- After few minutes, the user thinks the conversation is becoming worth recording. So they tap the resume button on the notification. Call recording resumes. 
- When the call ends, the record contains only the parts of the call when recording was not paused.

Is that possible to do? If not, I'd rather have the option you suggested, than not have it. I appreciate you reading my request and your time spent on it.

**Comment by chenxiaolong** [comment]
Hmm, I like what you described for the pause option.  That should be fairly simple to implement: BCR would grab the call audio for the entire duration of the call, but while "paused", it will throw away the data instead of writing to the output file.

Assuming that implementing ^^ doesn't complicate the code too much, I'll consider adding something similar to your original request (a "start recording"-type option), but it'll be based on the pause feature.

* New configuration option for the initial recording state: either `Recording` or `Paused`
* If the initial recording state is `Recording`, then BCR works as it does now. The user can pause and resume if needed.
* If the initial recording state is `Paused`, then BCR still reads the call audio, but throws it away until the user hits `Resume`. If the user never presses `Resume` in the notification, then BCR deletes the (empty) output file when the call ends.

---

In BCR, the lifetime of the recording is tied to the lifetime of a call. Changing this would introduce a lot of complexity. But I think this "always record, but discard data when paused" approach should hopefully keep things simple and reliable.

**Comment by bagarwa** [comment]
That would be a nice implementation. Looking forward to it.

**Comment by chenxiaolong** [comment]
The initial pause/resume implementation (button in the notification) has been implemented in #210 and will be included in version 1.28.

**Comment by chenxiaolong** [comment]
The new UI option for the initial recording state has been implemented in #211 and will be included in version 1.29.

**Comment by bagarwa** [comment]
Thank you.
