### ISSUE TITLE
Add number in file name

### ISSUE THREAD

**Issue by thewh1teagle** [chenxiaolong/BCR#230]
Currently the app is just recording calls and save them with file name that has the date of the record. 
I can't filter calls in my filesystem by their number. 
Can you add the option to have the dial number included in the saved file?

**Comment by chenxiaolong** [comment]
Hmm, this has been supported since the initial release. I wonder if Android isn't providing that information to BCR on your device. (It's supposed to always add the phone number and then additionally add the caller ID + contact name if you allow those permissions.)

Can you enable debug mode by long pressing BCR's version number, try to make a call, and then upload the log file that gets created in the output directory?

**Comment by thewh1teagle** [comment]
Sorry I just missed it, it actually add it to the name of every record.
The sound quality is great compared to the builtin recorder / another apps i used 
Thank you very much!

**Comment by chenxiaolong** [comment]
Great, glad you like the app!
