### ISSUE TITLE
Switching to WAV/PCM format causes the app to crash and then keeps crashing on every launch. 

### ISSUE THREAD

**Issue by bagarwa** [chenxiaolong/BCR#240]
I was previously using the OGG format. I was tapping the different format options, for no reason. When I tapped on WAV/PCM, the app crashed. From then on, whenever I try to launch BCR, the app immediately crashes. Cleared the app's data to manually reset it, and then am able to launch it and set it like I want.

Pixel 7 Pro, running Android 14 DP1, Magisk Canary 25206. 

BCR 1.32

(Sidenote - "Disable battery optimization" [option is greyed out](https://i.imgur.com/4tDkMFw.png) at "on" position! i.e. it is turned on and I can't disable it. But I checked in BCR app's app info page that "Battery" is set to "Unrestricted".)
(Should I create separate issues for these sidenotes.)

**Comment by chenxiaolong** [comment]
Oh, nice catch. I'm able to reproduce this. I'll investigate it and make a new release with the fix.

> (Sidenote - "Disable battery optimization" [option is greyed out](https://i.imgur.com/4tDkMFw.png) at "on" position! i.e. it is turned on and I can't disable it. But I checked in BCR app's app info page that "Battery" is set to "Unrestricted".)

This is because Android's API for this is kind of bad. An app can only request it to be turned on (which is the same as `Unrestricted`), but not to turn it off. I made the setting grayed out because there's nothing BCR can do to turn it off. I'm open to suggestions for better ways to handle the UI for this.

>  (Should I create separate issues for these sidenotes.)

No worries, I don't mind it either way :)

**Comment by chenxiaolong** [comment]
This is a bug in the material design 3 library. I'll see if I can work around it. If not, I'll downgrade to the previous version (before #239).
