### ISSUE TITLE
Shizuku support [question] [enhancement]

### ISSUE THREAD

**Issue by LCernei** [chenxiaolong/BCR#278]
Hi,
I was wondering: 
Can this app use [Shizuku](https://github.com/RikkaApps/Shizuku) instead of root / Magisk? (or even alongside Magisk?)
I understand that it requires additional development, but is it even possible?
Are there some permissions that BCR needs that are not available with Shizuku?
This can provide an easier installation and potentially a wider userbase.

**Comment by chenxiaolong** [comment]
Unfortunately, this is not possible. All call recording apps require the `CAPTURE_AUDIO_OUTPUT` permission and BCR additionally requires `CONTROL_INCALL_EXPERIENCE` to detect when calls begin/end. Neither of these system app permissions are available to adb/Shizuku (full list of permissions they support: https://github.com/aosp-mirror/platform_frameworks_base/blob/master/packages/Shell/AndroidManifest.xml).

**Comment by shahawi** [comment]
Hi,
Sorry to reopen the issue but I see that both permissions are now available in shizuku
https://github.com/aosp-mirror/platform_frameworks_base/blob/master/packages/Shell/AndroidManifest.xml

**Comment by chenxiaolong** [comment]
Nice! I hadn't seen that.

I looked into it today and unfortunately, while the permissions might be sufficient now, Shizuku does not support exporting services. There's no way to export BCR's `InCallService` in a way that Android will detect it and notify BCR of phone calls. Replacing that with Android's legacy call detection API might work, although that has limitations like not being able to properly handle call waiting, holding, conference calls, etc.

Accessing files, contacts, call information, etc. also needs to be split out from the recording logic because all of that requires access to a valid `Context`, which is not available from a Shizuku user service.

So with that said, I think it's theoretically possible for someone to write a limited call recorder for Android 14+ that uses Shizuku and does not require root. I won't be implementing this in BCR though. It would require a pretty significant rewrite and I don't really have any interest in doing it.

**Comment by shahawi** [comment]
Thank you for the clarification

**Comment by ElsAr4e** [comment]
In the meantime, even ACR Phone supports true call recording, and as far as I know, the SKVALEX Call Recorder does as well (according to Reddit; and the changelog states: “version 3.7.2: option ‘start recording on answer’ should now work with Shizuku”).

In any case, I achieved excellent results with ACR Phone using a fork of Shizuku (link: https://github.com/thedjchi/Shizuku).

Is it still the case that BCR will never support Shizuku-based call recording—neither in the original version nor in a fork?

**Comment by chenxiaolong** [comment]
Yep, I still have no plans for this.

**Comment by kitsumed** [comment]
> Is it still the case that BCR will never support Shizuku-based call recording—neither in the original version nor in a fork?

Currently working on a FOSS call recording application that uses Shizuku. It is already in a fully working state (at least on the Android Emulator and my 15 minutes test periods on a Samsung phone). (Edit: As of now, support Android 11-16, but 11 is very limited, for now, idk about the future)

Should release it this year if everything goes well! Will send the link back here if I remember it else there's a 99% probability I make a post on r/fossdroid on reddit.

EDIT: It's out
https://github.com/kitsumed/ShizuCallRecorder
https://www.reddit.com/r/fossdroid/comments/1tgxi0e/shizucallrecorder_record_phone_call_on_android/
After thinking about it, I don't think there's an issue with me sharing a alternative app. Feel free to delete this if it is (this is regarding to the previous text before editing this)

**Comment by ElsAr4e** [comment]
@kitsumed Will ShizuCallRecorder support root access on rooted devices in the future - similar to how ACR Phone supports both Shizuku and root- or will it remain Shizuku-only?

If not, it might make sense to cross-reference or pin the related projects on both GitHub pages. For example:

- ShizuCallRecorder could refer users who already have root access to Basic Call Recorder (BCR).
- And if the decision of @chenxiaolong remains that BCR will not support Shizuku in the foreseeable future, then BCR could point users to alternatives such as ShizuCallRecorder.

**Comment by kitsumed** [comment]
> @kitsumed Will ShizuCallRecorder support root access on rooted devices in the future - similar to how ACR Phone supports both Shizuku and root- or will it remain Shizuku-only?
> 
> If not, it might make sense to cross-reference or pin the related projects on both GitHub pages. For example:
> 
> - ShizuCallRecorder could refer users who already have root access to Basic Call Recorder (BCR).
> - And if the decision of @chenxiaolong remains that BCR will not support Shizuku in the foreseeable future, then BCR could point users to alternatives such as ShizuCallRecorder.

Shizuku itself support rooted users. I have no plan to support rooted phone as is outside of Shizuku, and already redirected some users to BCR on reddit when they asked the question. I will add a mention somewhere in the docs when I get time. Well if I dont forget. I had a similar mention before but somehow lost it got removed from the docs before released the project, probably due to file manipulations errors.

Btw we are looking for contributors, see our help wanted tags on issue. Thanks for the interest.
