### ISSUE TITLE
[Feature Request] Hide app icon option

### ISSUE THREAD

**Issue by symbuzzer** [chenxiaolong/BCR#287]
Can you add a feature to hide the icon from the application menu and open the application by dialing *#*#227#*#* from the phone application?

**Comment by chenxiaolong** [comment]
Sorry, this isn't something I plan to add because hiding app icons is no longer supported in Android 10+ without some hacky workarounds.

I'd suggest using a launcher that supports hiding apps instead. When hidden, BCR can still be opened by long pressing its quick settings icon and then pressing Open.
