### ISSUE TITLE
Offer a single-string method to alter filename format

### ISSUE THREAD

**Issue by blackwind** [chenxiaolong/BCR#288]
I assume the method to alter filename format currently in place is there because there's a Kotlin library for it -- and hey, I'm always in favor of the KISS design philosophy -- but boy, is it ever clunky and inflexible.

Here's what I want, having used this format for my VoIP calls for years and years now: `Tim Johnson (2023-04-15 @ 1.25.34 PM).m4a`

As an example, Winamp/foobar2000 [advanced title formatting (ATF) script](https://www.meggamusic.co.uk/winamp/docs/help/atf/atf.htm) makes this incredibly easy: `$if3(${contact_name},${caller_name},${phone_number},Anonymous Caller) (${date:yyyy-MM-dd @ h.mm.ss a})`

Problems with the current method:
* There's no ability to include spaces as far as I can tell
* `default` supports a single fallback if a variable is empty but not multiple like ATF's `$if3()`
* Numbering each segment by hand is clunky and prone to user error
* `prefix` and `suffix` are valuable given the current paradigm, but could easily be replaced by ATF's `[]`, which only includes the contained data if all variables are set (`[SIM${sim_slot}]` would dump "SIM" as well if `${sim_slot}` wasn't set)
* If this functionality was part of the app, the app could immediately tell you if there's a syntax error so there'd be no surprises
* If you still want to hide this functionality, it'd be better hidden behind the debug mode toggle than in a separate file you have to download, place, and edit

Implementing ATF in its entirety, of course, would be overkill (unless there's a library for that), but the items I've specifically called out are the important ones. Perhaps a more Java/Kotlin-like syntax for them would be prudent.

I do understand that my preferred filename format would break the retention feature. This could be worked around by examining file timestamps instead of filenames, but personally, I want to retain all recordings, would never use that feature, and don't care if it gets amended.

**Comment by chenxiaolong** [comment]
I'll have to think about this a bit. I hate the way things currently work too.

> * There's no ability to include spaces as far as I can tell

It's ugly, but I believe the Java properties format lets you do `<key> = \ `.

> * Numbering each segment by hand is clunky and prone to user error

Agreed.

> * `prefix` and `suffix` are valuable given the current paradigm, but could easily be replaced by ATF's `[]`, which only includes the contained data if all variables are set (`[SIM${sim_slot}]` would dump "SIM" as well if `${sim_slot}` wasn't set)

That's nice. I originally (before the current format was implemented) wanted to do a bash-style syntax, like:

```bash
${date}${direction+_${direction}}${sim_slot+_sim${sim_slot}}${phone_number+_${phone_number}}${caller_name+_${caller_name}}${contact_name+_${contact_name}}
```

but I gave up on that since the implementation was more complicated than I like. If I end up implementing a new format string system, it'll have to be something with an existing Java/Kotlin library. In the spirit of keeping things simple, I don't want to write a new custom parser for BCR.

> * If this functionality was part of the app, the app could immediately tell you if there's a syntax error so there'd be no surprises
> * If you still want to hide this functionality, it'd be better hidden behind the debug mode toggle than in a separate file you have to download, place, and edit

Oh yeah, that was 100% intentional because in its current state, the filename templates are not a feature I really want to support. If the replacement ends up being a lot better, I'll consider making it an option in the UI.

> I do understand that my preferred filename format would break the retention feature. This could be worked around by examining file timestamps instead of filenames, but personally, I want to retain all recordings, would never use that feature, and don't care if it gets amended.

I could probably update the UI to disable/remove the retention feature if the date isn't at the beginning of the filename (or maybe find some smarter way to guess). File modification timestamps are broken on some devices when the file access goes through the storage access framework (any custom output directory), so I unfortunately can't use that. (I've seen some devices where the mtime is always Unix timestamp 0, which would cause every recording to be deleted if the user tried to use the feature.)

**Comment by chenxiaolong** [comment]
Ah screw it, I'll just implement a custom parser. I can't find any good libraries for this sort of thing.

Tentative plan:

- `{}` for referencing variables. It can take an optional argument similar to the current setup. Eg. `{phone_number}`, `{date}`, `{date:yyyyMMdd+HHmmss}`.
- `[]` for specifying fallbacks. Eg. `[_{contact_name}|_{caller_name}|Unknown]`. It will go through each enclosed section separated by `|` from left to right until it finds a section that can be evaluated successfully. There is an implicit empty section at the end (`[{var}]` is the same as `[{var}|]`) so that this same syntax can be used to specify an optional section without a fallback.
- The `\`, `[`, `]`, `{`, `}`, and `|` characters must be escaped with a preceding `\` to add them to the filename verbatim.
- The existing `bcr.properties` will be migrated to the new setting automatically and the config will be renamed to `bcr.properties.migrated`. Besides the migration path, nothing will use the config file anymore. That'll remove a major source of slowness and recording delays on some devices due to Android storage access framework bugs.

The default template would be (keeping the same format):
```
{date}[_{direction}][_sim{sim_slot}][_{phone_number}][_{caller_name}][_{contact_name}]
```

The custom template from your original post could be achieved with:

```
[{contact_name}|{caller_name}|{phone_number}|Anonymous Caller] ({date:yyyy-MM-dd @ h.mm.ss a})
```

**Comment by chenxiaolong** [comment]
OK, I have an implementation of this working locally, but with no UI option yet.

The only change I made from my original proposal is that `[{var}]` does not fall back to the empty string. The user will have to be explicit: `[{var}|]`. The reason is it breaks nested usage of `[]`, like:

```
{phone_number}[ ([{contact_name}|{caller_name}])]
```

With the implicit empty string fallback, if both variables are undefined, that would evaluate to `123456789 ()`.

Also managed to improve the timestamp parsing for the file retention feature. It'll work as long as the date is at the beginning of the filename or has fixed text right in front of it. Eg. with the custom template:

```
[{contact_name}|{caller_name}|{phone_number}|Anonymous Caller] ({date:yyyy-MM-dd @ h.mm.ss a})
```

```
I/RecorderThread/192(26067): Retention period is PT8760H
E/TEST     (26067): Parsed 2023-04-14T21:59:54 from +18056377243 (2023-04-14 @ 9.59.54 PM).m4a
I/RecorderThread/192(26067): Recording thread completed
D/RecorderThread/192(26067): Stopping log file
```

It'll work because of the ` (` prior to the date. It'll still work if ` (` shows up in the filename multiple times because it tries to parse at every instance of it. A template with no prefix before the date like `{phone_number}{date}` should be the only case where things don't work and that's visually ugly enough that hopefully nobody will be doing that.
