### ISSUE TITLE
How to save to cloud storage

### ISSUE THREAD

**Issue by greatcoder88** [chenxiaolong/BCR#30]
The description mentions that it supports to save the recording to cloud storage. How can we save the recording to cloud storage directly ?
And if let's say network is not available, is there a fallback to store it locally on sd card or internal storage ?

**Comment by Savaturkey** [comment]
As far as I know, it will not record on the cloud. Saving a basic search on its name, don't expect a lot of features.

**Comment by greatcoder88** [comment]
> As far as I know, it will not record on the cloud. Saving a basic call Recorder on its name, don't expect a lot of features.

As per the feature it supports cloud storage. I will prefer the developer respond to my query.
 - Supports Android's Storage Access Framework (can record to SD cards, USB devices, cloud storage, etc.)

**Comment by chenxiaolong** [comment]
Sorry, I thought that because I'm using Android's Storage Access Framework that cloud storage would work, but it looks like Android doesn't support that: https://issuetracker.google.com/issues/135636079

Storage Access Framework can only use cloud providers when selecting a file, not a folder.

I'll remove the mention of cloud storage from the README. BCR will not support anything besides SAF, so cloud storage won't work.
