### ISSUE TITLE
BCR keeps stopping on Magisk Delta

### ISSUE THREAD

**Issue by lomirus** [chenxiaolong/BCR#326]
It's fine at start, but several days ago I switched to Magisk Delta and enabled the MagiskHide, and it seems that from then on the BCR cannot launch anymore.

BCR Version: 1.41
Android Version: 13

![product_logo_48](https://user-images.githubusercontent.com/21173956/236200781-7ab66850-f01c-42c3-9651-55e02d27f802.png)

**Comment by chenxiaolong** [comment]
Just to make sure this isn't related to #303, can you give this test build a try? https://github.com/chenxiaolong/BCR/issues/303#issuecomment-1532007424

If it's still broken with that build, you'll probably need to switch back to official Magisk. Magisk Delta's module handling has significant differences to what official Magisk does.

**Comment by lomirus** [comment]
Still keeps stopping after trying the [#303 (comment)](https://github.com/chenxiaolong/BCR/issues/303#issuecomment-1532007424). Do you have the plan to fix this problem for Magisk Delta?

**Comment by chenxiaolong** [comment]
Darn. There's probably not much I can do if that's the case. BCR only uses the most basic Magisk module feature of putting two files in `/system/etc/permissions` and `/system/priv-app`. I don't know why that would be broken with Magisk Delta.

**Comment by athulkrishna2015** [comment]
I have the same issue

**Comment by J4CKED** [comment]
No problem for me. 
I'm using Magisk Delta version 017cca27, magisk hide ON and old BCR v1.23. Android 12.

**Comment by athulkrishna2015** [comment]
--------- beginning of crash
05-07 12:12:17.519 30918 30918 E AndroidRuntime: FATAL EXCEPTION: main
05-07 12:12:17.519 30918 30918 E AndroidRuntime: Process: com.chiller3.bcr, PID: 30918
05-07 12:12:17.519 30918 30918 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chiller3.bcr/com.chiller3.bcr.SettingsActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
05-07 12:12:17.519 30918 30918 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
05-07 12:12:17.519 30918 30918 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
05-07 12:12:17.519 30918 30918 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
05-07 12:12:17.519 30918 30918 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
05-07 12:12:17.519 30918 30918 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
05-07 12:12:17.519 30918 30918 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
05-07 12:12:17.519 30918 30918 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-07 12:12:17.519 30918 30918 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
05-07 12:12:17.519 30918 30918 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
05-07 12:12:17.519 30918 30918 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7872)
05-07 12:12:17.519 30918 30918 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-07 12:12:17.519 30918 30918 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
05-07 12:12:17.519 30918 30918 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
05-07 12:12:17.519 30918 30918 E AndroidRuntime: Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
05-07 12:12:17.519 30918 30918 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(Unknown Source:676)
05-07 12:12:17.519 30918 30918 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(SourceFile:6)
05-07 12:12:17.519 30918 30918 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.setContentView(SourceFile:2)
05-07 12:12:17.519 30918 30918 E AndroidRuntime: 	at com.chiller3.bcr.SettingsActivity.onCreate(Unknown Source:6)
05-07 12:12:17.519 30918 30918 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8311)
05-07 12:12:17.519 30918 30918 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8290)
05-07 12:12:17.519 30918 30918 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1420)
05-07 12:12:17.519 30918 30918 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
05-07 12:12:17.519 30918 30918 E AndroidRuntime: 	... 12 more
05-07 17:03:55.982  5707  5707 E AndroidRuntime: FATAL EXCEPTION: main
05-07 17:03:55.982  5707  5707 E AndroidRuntime: Process: com.chiller3.bcr, PID: 5707
05-07 17:03:55.982  5707  5707 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chiller3.bcr/com.chiller3.bcr.SettingsActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
05-07 17:03:55.982  5707  5707 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
05-07 17:03:55.982  5707  5707 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
05-07 17:03:55.982  5707  5707 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
05-07 17:03:55.982  5707  5707 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
05-07 17:03:55.982  5707  5707 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
05-07 17:03:55.982  5707  5707 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
05-07 17:03:55.982  5707  5707 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-07 17:03:55.982  5707  5707 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
05-07 17:03:55.982  5707  5707 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
05-07 17:03:55.982  5707  5707 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7872)
05-07 17:03:55.982  5707  5707 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-07 17:03:55.982  5707  5707 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
05-07 17:03:55.982  5707  5707 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
05-07 17:03:55.982  5707  5707 E AndroidRuntime: Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
05-07 17:03:55.982  5707  5707 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(Unknown Source:676)
05-07 17:03:55.982  5707  5707 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(SourceFile:6)
05-07 17:03:55.982  5707  5707 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.setContentView(SourceFile:2)
05-07 17:03:55.982  5707  5707 E AndroidRuntime: 	at com.chiller3.bcr.SettingsActivity.onCreate(Unknown Source:6)
05-07 17:03:55.982  5707  5707 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8311)
05-07 17:03:55.982  5707  5707 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8290)
05-07 17:03:55.982  5707  5707 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1420)
05-07 17:03:55.982  5707  5707 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
05-07 17:03:55.982  5707  5707 E AndroidRuntime: 	... 12 more
05-07 17:05:16.532  7984  7984 E AndroidRuntime: FATAL EXCEPTION: main
05-07 17:05:16.532  7984  7984 E AndroidRuntime: Process: com.chiller3.bcr, PID: 7984
05-07 17:05:16.532  7984  7984 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chiller3.bcr/com.chiller3.bcr.SettingsActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
05-07 17:05:16.532  7984  7984 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
05-07 17:05:16.532  7984  7984 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
05-07 17:05:16.532  7984  7984 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
05-07 17:05:16.532  7984  7984 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
05-07 17:05:16.532  7984  7984 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
05-07 17:05:16.532  7984  7984 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
05-07 17:05:16.532  7984  7984 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-07 17:05:16.532  7984  7984 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
05-07 17:05:16.532  7984  7984 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
05-07 17:05:16.532  7984  7984 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7872)
05-07 17:05:16.532  7984  7984 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-07 17:05:16.532  7984  7984 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
05-07 17:05:16.532  7984  7984 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
05-07 17:05:16.532  7984  7984 E AndroidRuntime: Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
05-07 17:05:16.532  7984  7984 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(Unknown Source:676)
05-07 17:05:16.532  7984  7984 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(SourceFile:6)
05-07 17:05:16.532  7984  7984 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.setContentView(SourceFile:2)
05-07 17:05:16.532  7984  7984 E AndroidRuntime: 	at com.chiller3.bcr.SettingsActivity.onCreate(Unknown Source:6)
05-07 17:05:16.532  7984  7984 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8311)
05-07 17:05:16.532  7984  7984 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8290)
05-07 17:05:16.532  7984  7984 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1420)
05-07 17:05:16.532  7984  7984 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
05-07 17:05:16.532  7984  7984 E AndroidRuntime: 	... 12 more
05-07 17:05:24.076  8062  8062 E AndroidRuntime: FATAL EXCEPTION: main
05-07 17:05:24.076  8062  8062 E AndroidRuntime: Process: com.chiller3.bcr, PID: 8062
05-07 17:05:24.076  8062  8062 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chiller3.bcr/com.chiller3.bcr.SettingsActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
05-07 17:05:24.076  8062  8062 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
05-07 17:05:24.076  8062  8062 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
05-07 17:05:24.076  8062  8062 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
05-07 17:05:24.076  8062  8062 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
05-07 17:05:24.076  8062  8062 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
05-07 17:05:24.076  8062  8062 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
05-07 17:05:24.076  8062  8062 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-07 17:05:24.076  8062  8062 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
05-07 17:05:24.076  8062  8062 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
05-07 17:05:24.076  8062  8062 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7872)
05-07 17:05:24.076  8062  8062 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-07 17:05:24.076  8062  8062 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
05-07 17:05:24.076  8062  8062 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
05-07 17:05:24.076  8062  8062 E AndroidRuntime: Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
05-07 17:05:24.076  8062  8062 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(Unknown Source:676)
05-07 17:05:24.076  8062  8062 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(SourceFile:6)
05-07 17:05:24.076  8062  8062 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.setContentView(SourceFile:2)
05-07 17:05:24.076  8062  8062 E AndroidRuntime: 	at com.chiller3.bcr.SettingsActivity.onCreate(Unknown Source:6)
05-07 17:05:24.076  8062  8062 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8311)
05-07 17:05:24.076  8062  8062 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8290)
05-07 17:05:24.076  8062  8062 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1420)
05-07 17:05:24.076  8062  8062 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
05-07 17:05:24.076  8062  8062 E AndroidRuntime: 	... 12 more
05-08 12:35:47.944 14037 14037 E AndroidRuntime: FATAL EXCEPTION: main
05-08 12:35:47.944 14037 14037 E AndroidRuntime: Process: com.chiller3.bcr, PID: 14037
05-08 12:35:47.944 14037 14037 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chiller3.bcr/com.chiller3.bcr.SettingsActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
05-08 12:35:47.944 14037 14037 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
05-08 12:35:47.944 14037 14037 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
05-08 12:35:47.944 14037 14037 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
05-08 12:35:47.944 14037 14037 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
05-08 12:35:47.944 14037 14037 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
05-08 12:35:47.944 14037 14037 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
05-08 12:35:47.944 14037 14037 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-08 12:35:47.944 14037 14037 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
05-08 12:35:47.944 14037 14037 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
05-08 12:35:47.944 14037 14037 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7872)
05-08 12:35:47.944 14037 14037 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-08 12:35:47.944 14037 14037 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
05-08 12:35:47.944 14037 14037 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
05-08 12:35:47.944 14037 14037 E AndroidRuntime: Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
05-08 12:35:47.944 14037 14037 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(Unknown Source:676)
05-08 12:35:47.944 14037 14037 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(SourceFile:6)
05-08 12:35:47.944 14037 14037 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.setContentView(SourceFile:2)
05-08 12:35:47.944 14037 14037 E AndroidRuntime: 	at com.chiller3.bcr.SettingsActivity.onCreate(Unknown Source:6)
05-08 12:35:47.944 14037 14037 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8311)
05-08 12:35:47.944 14037 14037 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8290)
05-08 12:35:47.944 14037 14037 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1420)
05-08 12:35:47.944 14037 14037 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
05-08 12:35:47.944 14037 14037 E AndroidRuntime: 	... 12 more
--------- beginning of main
05-08 16:08:09.458  3904  3904 E om.chiller3.bcr: Not starting debugger since process cannot load the jdwp agent.
05-08 16:08:09.482  3904  3904 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10221; state: ENABLED
05-08 16:08:09.502  3904  3904 W ziparchive: Unable to open '/system/priv-app/com.chiller3.bcr/app-release.dm': No such file or directory
05-08 16:08:09.502  3904  3904 W ziparchive: Unable to open '/system/priv-app/com.chiller3.bcr/app-release.dm': No such file or directory
05-08 16:08:09.524  3904  3904 W om.chiller3.bcr: JIT profile information will not be recorded: profile file does not exist.
05-08 16:08:09.533  3904  3904 V GraphicsEnvironment: ANGLE Developer option for 'com.chiller3.bcr' set to: 'default'
05-08 16:08:09.533  3904  3904 V GraphicsEnvironment: ANGLE GameManagerService for com.chiller3.bcr: false
05-08 16:08:09.533  3904  3904 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
05-08 16:08:09.535  3904  3904 D NetworkSecurityConfig: No Network Security Config specified, using platform default
05-08 16:08:09.536  3904  3904 D NetworkSecurityConfig: No Network Security Config specified, using platform default
05-08 16:08:09.804  3904  3904 D Preferences: Looking for legacy filename template in: file:///storage/emulated/0/Android/data/com.chiller3.bcr/files
05-08 16:08:09.806  3904  3904 D Preferences: No legacy filename template to migrate
05-08 16:08:09.838  3904  3904 E om.chiller3.bcr: Resource 7f10001c is a complex map type.
05-08 16:08:09.838  3904  3904 W PackageManager: Failure retrieving text 0x7f10001c in package com.chiller3.bcr
05-08 16:08:09.838  3904  3904 W PackageManager: android.content.res.Resources$NotFoundException: String resource ID #0x7f10001c
05-08 16:08:09.838  3904  3904 W PackageManager: 	at android.content.res.Resources.getText(Resources.java:453)
05-08 16:08:09.838  3904  3904 W PackageManager: 	at android.app.ApplicationPackageManager.getText(ApplicationPackageManager.java:2350)
05-08 16:08:09.838  3904  3904 W PackageManager: 	at android.content.pm.ComponentInfo.loadUnsafeLabel(ComponentInfo.java:139)
05-08 16:08:09.838  3904  3904 W PackageManager: 	at android.content.pm.PackageItemInfo.loadLabel(PackageItemInfo.java:212)
05-08 16:08:09.838  3904  3904 W PackageManager: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3574)
05-08 16:08:09.838  3904  3904 W PackageManager: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
05-08 16:08:09.838  3904  3904 W PackageManager: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
05-08 16:08:09.838  3904  3904 W PackageManager: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
05-08 16:08:09.838  3904  3904 W PackageManager: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
05-08 16:08:09.838  3904  3904 W PackageManager: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
05-08 16:08:09.838  3904  3904 W PackageManager: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-08 16:08:09.838  3904  3904 W PackageManager: 	at android.os.Looper.loopOnce(Looper.java:201)
05-08 16:08:09.838  3904  3904 W PackageManager: 	at android.os.Looper.loop(Looper.java:288)
05-08 16:08:09.838  3904  3904 W PackageManager: 	at android.app.ActivityThread.main(ActivityThread.java:7872)
05-08 16:08:09.838  3904  3904 W PackageManager: 	at java.lang.reflect.Method.invoke(Native Method)
05-08 16:08:09.838  3904  3904 W PackageManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
05-08 16:08:09.838  3904  3904 W PackageManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
05-08 16:08:09.851  3904  3904 D AppCompatDelegate: Checking for metadata for AppLocalesMetadataHolderService : Service not found
05-08 16:08:09.857  3904  3904 E om.chiller3.bcr: Invalid ID 0x00000000.
05-08 16:08:09.878  3904  3904 D AndroidRuntime: Shutting down VM
05-08 16:08:09.879  3904  3904 E AndroidRuntime: FATAL EXCEPTION: main
05-08 16:08:09.879  3904  3904 E AndroidRuntime: Process: com.chiller3.bcr, PID: 3904
05-08 16:08:09.879  3904  3904 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chiller3.bcr/com.chiller3.bcr.SettingsActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
05-08 16:08:09.879  3904  3904 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
05-08 16:08:09.879  3904  3904 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
05-08 16:08:09.879  3904  3904 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
05-08 16:08:09.879  3904  3904 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
05-08 16:08:09.879  3904  3904 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
05-08 16:08:09.879  3904  3904 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
05-08 16:08:09.879  3904  3904 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-08 16:08:09.879  3904  3904 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
05-08 16:08:09.879  3904  3904 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
05-08 16:08:09.879  3904  3904 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7872)
05-08 16:08:09.879  3904  3904 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-08 16:08:09.879  3904  3904 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
05-08 16:08:09.879  3904  3904 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
05-08 16:08:09.879  3904  3904 E AndroidRuntime: Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
05-08 16:08:09.879  3904  3904 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(Unknown Source:676)
05-08 16:08:09.879  3904  3904 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(SourceFile:6)
05-08 16:08:09.879  3904  3904 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.setContentView(SourceFile:2)
05-08 16:08:09.879  3904  3904 E AndroidRuntime: 	at com.chiller3.bcr.SettingsActivity.onCreate(Unknown Source:6)
05-08 16:08:09.879  3904  3904 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8311)
05-08 16:08:09.879  3904  3904 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8290)
05-08 16:08:09.879  3904  3904 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1420)
05-08 16:08:09.879  3904  3904 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
05-08 16:08:09.879  3904  3904 E AndroidRuntime: 	... 12 more
05-08 16:08:09.881  3904  3904 D OutputDirUtils: Creating crash.log with MIME type text/plain in file:///storage/emulated/0/Android/data/com.chiller3.bcr/files
05-08 16:08:09.886  3904  3904 E RecorderApplication: Saving logcat to file:///storage/emulated/0/Android/data/com.chiller3.bcr/files/crash.log.txt due to uncaught exception in Thread[main,5,main]
05-08 16:08:09.886  3904  3904 E RecorderApplication: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chiller3.bcr/com.chiller3.bcr.SettingsActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
05-08 16:08:09.886  3904  3904 E RecorderApplication: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
05-08 16:08:09.886  3904  3904 E RecorderApplication: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
05-08 16:08:09.886  3904  3904 E RecorderApplication: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
05-08 16:08:09.886  3904  3904 E RecorderApplication: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
05-08 16:08:09.886  3904  3904 E RecorderApplication: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
05-08 16:08:09.886  3904  3904 E RecorderApplication: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
05-08 16:08:09.886  3904  3904 E RecorderApplication: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-08 16:08:09.886  3904  3904 E RecorderApplication: 	at android.os.Looper.loopOnce(Looper.java:201)
05-08 16:08:09.886  3904  3904 E RecorderApplication: 	at android.os.Looper.loop(Looper.java:288)
05-08 16:08:09.886  3904  3904 E RecorderApplication: 	at android.app.ActivityThread.main(ActivityThread.java:7872)
05-08 16:08:09.886  3904  3904 E RecorderApplication: 	at java.lang.reflect.Method.invoke(Native Method)
05-08 16:08:09.886  3904  3904 E RecorderApplication: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
05-08 16:08:09.886  3904  3904 E RecorderApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
05-08 16:08:09.886  3904  3904 E RecorderApplication: Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
05-08 16:08:09.886  3904  3904 E RecorderApplication: 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(Unknown Source:676)
05-08 16:08:09.886  3904  3904 E RecorderApplication: 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(SourceFile:6)
05-08 16:08:09.886  3904  3904 E RecorderApplication: 	at androidx.appcompat.app.AppCompatActivity.setContentView(SourceFile:2)
05-08 16:08:09.886  3904  3904 E RecorderApplication: 	at com.chiller3.bcr.SettingsActivity.onCreate(Unknown Source:6)
05-08 16:08:09.886  3904  3904 E RecorderApplication: 	at android.app.Activity.performCreate(Activity.java:8311)
05-08 16:08:09.886  3904  3904 E RecorderApplication: 	at android.app.Activity.performCreate(Activity.java:8290)
05-08 16:08:09.886  3904  3904 E RecorderApplication: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1420)
05-08 16:08:09.886  3904  3904 E RecorderApplication: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
05-08 16:08:09.886  3904  3904 E RecorderApplication: 	... 12 more

**Comment by athulkrishna2015** [comment]
> I have the same issue

Fixed the issue by 
Installing the apk extracted from the .zip file
After flashing the module

**Comment by AlphaDE** [comment]
This also solved the same issue with BCR 1.56 and Magisk Delta 26.403 here
