### ISSUE TITLE
recoding button request

### ISSUE THREAD

**Issue by hamid430110** [chenxiaolong/BCR#346]
Hi your recording module works good but if it is possible change the action of recoding button in dialer.
suppose that i have a call (unknown or fom my contact list ) when i start my calling if it was important for me i will push recording button and program start to record ,and if i do not want want to record any thing , i will do nothing , it is very simple action you can put to mode in first menu 1- manual     2-auto

my device is mi a1 - android 13 (custom rom) your module has no poblem and work in auto mode well only put my request in next version

thanks

**Comment by Derkish** [comment]
The problem with features like that, is it can get in the way of people who just want to set and forget that the app is running.

**Comment by hamid430110** [comment]
yes you are right but if  is possible  for you make a new version with this option and place a note for this change , it is up to every one to use it with this change.
thanks i am sure that  many people like me need this type of your call recorder.

**Comment by hamid430110** [comment]
> yes you are right but if is possible for you make a new version with this option and place a note for this change , it is up to every one to use it with this change.
> thanks i am sure that many people like me need this type of your call recorder.

**Comment by hamid430110** [comment]
I think after instalation of this module it is runing in background and only wait for push call record button when the program is manual mode that i have suggested and if the user select auto mode program work like before. is it correct?

**Comment by chenxiaolong** [comment]
> suppose that i have a call (unknown or fom my contact list ) when i start my calling if it was important for me i will push recording button and program start to record ,and if i do not want want to record any thing , i will do nothing , it is very simple action you can put to mode in first menu 1- manual 2-auto

This is already possible with the new auto-record rules in version 1.42. Just turn off the `Unknown calls` and `All other calls` options in BCR (or for specific contacts if you want). If you want to record a call, you can hit the button in BCR's notification during the call. (Unlike other call recorders, you can even do this in the middle of the call and the recording will still contain the full call.)

> possible change the action of recoding button in dialer.

Changing or adding buttons in the dialer is impossible without using Xposed/LSPosed and the code to do that is different across every Android OEM skin. For updatable dialers like Google Dialer, it'd have to change with each dialer app update too. I don't want to play this sort of cat-and-mouse game, which is why everything is done from BCR's notification.

**Comment by hamid430110** [comment]
Hi i have checked bcr with your help and work well .thanks
