### ISSUE TITLE
Sometimes it records the voice of the other party, sometimes it doesn't.

### ISSUE THREAD

**Issue by ercanzynk01** [chenxiaolong/BCR#365]
I installed the application with root. But sometimes it records the voice of the other party, sometimes it doesn't, and there is no sound at first for 5-10 seconds. Then only my voice is heard. How can I solve this output format?

**Comment by chenxiaolong** [comment]
Unfortunately, there's not much you can do besides trying different custom ROMs.

The contents of the audio is entirely determined by the modem firmware + kernel + Android's audio drivers. BCR only records what it receives from the audio driver to a file. It never modifies the audio and it can't tell the difference between your own audio and the other party's audio because the audio driver merges them before the audio stream reaches BCR.
