### ISSUE TITLE
Empty recording

### ISSUE THREAD

**Issue by windscolorme** [chenxiaolong/BCR#40]
Hi, after making a call, I get a record file with [nothing.(<10KB)]
I use this mod apk or magisk mod and also get Empty recording, realme x2 with pixel extended 4.3 android12 . (https://github.com/jacopotediosi/GoogleDialerMod/issues/12)
https://github.com/jacopotediosi/GoogleDialerMod-Magisk
How can I debug this, thanks! 
[logcat.txt](https://github.com/chenxiaolong/BCR/files/8788030/logcat.txt)

> 05-27 23:58:33.989 D/android.hardware.audio@2.0-service(768): Failed to fetch the lookup information of the device 00000004 
05-27 23:58:33.989 D/ACDB-LOADER(768): Error: ACDB AFE returned = -19
05-27 23:58:33.989 D/ACDB-LOADER(768): ACDB -> AUDIO_SET_AFE_CAL cal_type[17] acdb_id[4]
05-27 23:58:33.989 D/ACDB-LOADER(768): ACDB -> send_hw_delay : acdb_id = 4 path = 1
05-27 23:58:33.989 D/ACDB-LOADER(768): ACDB -> ACDB_AVSYNC_INFO: ACDB_CMD_GET_DEVICE_PROPERTY
05-27 23:58:33.989 D/audio_hw_primary(768): enable_audio_route: apply mixer and update path: incall-rec-uplink-and-downlink
05-27 23:58:33.989 D/audio_route(768): Apply path: incall-rec-uplink-and-downlink
05-27 23:58:33.989 D/audio_hw_primary(768): select_devices: acdb_id_in: 41
05-27 23:58:33.989 D/audio_hw_primary(768): select_devices: done
05-27 23:58:33.990 W/OggWriter(3831): failed to read next buffer

**Comment by chenxiaolong** [comment]
Could you give these 2 debug builds a try?

* [BCR-1.4.r2.gb4652df-debug-dump_raw_wave.zip](https://github.com/chenxiaolong/BCR/files/8790112/BCR-1.4.r2.gb4652df-debug-dump_raw_wave.zip)
* [BCR-1.4.r3.gaa21633-debug-dump_raw_wave_16kHz.zip](https://github.com/chenxiaolong/BCR/files/8790113/BCR-1.4.r3.gaa21633-debug-dump_raw_wave_16kHz.zip)

These debug builds disable encoding/compression and will dump the raw audio that Android provides into a `.wav` file.

If it still produces empty files, then either the device doesn't support call recording or the ROM you're running isn't compatible. Call recording requires the modem, kernel, vendor firmware, and ROM to all be compatible for it to work. On some devices, even the original ROM won't work because the manufacturer never bothered to make the feature work.
 
---

 ```
 7621 05-27 23:58:34.076 I/RecorderInCallService(3831): Recording completed: 158: content://com.android.externalstorage.documents/tree/678F-BA11%3AMusic%2FRecords/document/678F-BA11%3AMusic%2FRecords%2F20220527_235815.896%2B0800_out_[edit].oga
```
(Also, thanks for the `[edit]`. I'll make sure the next version of BCR no longer logs the phone number.)

**Comment by windscolorme** [comment]
Hi, thanks for your debug builds, I think this is ROM's problem?(sorry, I don't have ability to confirm this) I am trying to contact the ROM's support.
Here is the logcat file:
[logcat.txt](https://github.com/chenxiaolong/BCR/files/8790360/logcat.txt)
[logcat.txt](https://github.com/chenxiaolong/BCR/files/8790362/logcat.txt)

**Comment by zaingraphiics** [comment]
I'm using BCR 1.4 but facing same issue.

**Comment by windscolorme** [comment]
> I'm using BCR 1.4 but facing same issue.
Hi, I tried this call recorder and also failed. (https://gitlab.com/axet/android-call-recorder)
The rom maintainer said that "Call recording on custom roms Is difficult"

**Comment by zaingraphiics** [comment]
> > I'm using BCR 1.4 but facing same issue.
> 
> Hi, I tried this call recorder and also failed. (https://gitlab.com/axet/android-call-recorder)
> The rom maintainer said that "Call recording on custom roms is difficult"
> And axet said "MOST PHONES DOES NOT SUPPORT CALL RECORDING. Blame Google or your phone manufacturer not me!" on gitlab

Somehow recording started working

**Comment by zaingraphiics** [comment]
![Screenshot_20220528-213509_BCR.png](https://user-images.githubusercontent.com/37476697/170833359-bb30174a-c9f5-4b43-afac-a554a5c6bd6b.png)

Using these settings

**Comment by zaingraphiics** [comment]
It again stopped working after the latest update

**Comment by MagTun** [comment]
I had the same problem (lineageOS 20, magisk 26.1). I first tried Axet Call Recorder app and I got empty recordings. Then I tried this app and also got empty recordings. Then I switched to FLAC as explained by @bolltzain and it's working!
