### ISSUE TITLE
Import & Export config

### ISSUE THREAD

**Issue by symbuzzer** [chenxiaolong/BCR#403]
The kernel loaded with the AOSP-based ROM I am using does not have KernelSU support. For this reason, I have to reinstall the KernelSU supported kernel after every ROM update. The BCR configuration is reset with each new install. For this reason, such a feature would be very useful.

**Comment by chenxiaolong** [comment]
I'll consider it. While it's possible to do a complete export, it's not possible to do a complete import. In particular, the output directory is tied to Android URI permissions. Android will not allow access to the directory unless the user goes through the process of picking it again.

In the meantime, I'd suggest using an app like Neo-Backup to back up and restore BCR's data. If I remember correctly, it can use root access to save and restore URI permissions.

---

Alternatively, if your ROM allows `/system` to be modified, you could also consider flashing BCR from recovery. This would install it directly to `/system` instead of using Magisk/KernelSU's module system. This method allows BCR to persist across ROM updates due to a `/system/addon.d/` script.
