### ISSUE TITLE
Delete Record

### ISSUE THREAD

**Issue by Savaturkey** [chenxiaolong/BCR#433]
I enjoy using your application. There is a little problem.It records, but I set a period of 7 days for it to delete previous recordings, but it doesn't.

**Comment by chenxiaolong** [comment]
Can you enable debug mode by long pressing BCR's version number, make a call, and then upload the log file that it saves in the output directory?

**Comment by Savaturkey** [comment]
[29-09-2023 ~ 09_34_out _ 08507240724_İş BANKASI.log.txt](https://github.com/chenxiaolong/BCR/files/12761650/29-09-2023.09_34_out._.08507240724_Is.BANKASI.log.txt)

Can you open the file? How can I send this to you?

**Comment by chenxiaolong** [comment]
Thanks for the logs. I think it's caused by the `dd-MM-yyyy ~ HH:mm` timestamp format. Android does not support `:` inside filenames, so the `HH:mm` gets renamed to `HH_mm` when the file is saved. Later, when BCR looks at the old files, the colon is missing, so it doesn't understand the timestamp and nothing is cleaned up.

I think you can fix this by simply changing `:` to `_` in your filename template.

**Comment by Savaturkey** [comment]
My log format is {date:dd-MM-yyyy ~ HH:mm}[_{direction}|][ _{phone_number}|][_[{contact_name}|{caller_name}|{call_log_name}]|] output like this

**Comment by Savaturkey** [comment]
The output is also 28-09-2023 ~ 14_59_in _ 05426443392_Halit & Serhan KAFADAR  In this way, it is very understandable. If this is the problem, I would definitely prefer to delete the records myself.
