### ISSUE TITLE
bcr can't record calls

### ISSUE THREAD

**Issue by AlirezaSharifi8290** [chenxiaolong/BCR#440]
hey, i'm using lineage 20, i installed bcr trough magisk
and it's not working
it gives me this error
btw there's a call recording option in this rom but i have to click record every time that i call
![Screenshot_20231006-163347_Trebuchet](https://github.com/chenxiaolong/BCR/assets/118694245/eff139f6-3ea6-4873-873a-3dd3e03e6aba)

**Comment by chenxiaolong** [comment]
Which device are you using? Can you link to the exact LineageOS ROM?

From the error, it looks like true call recording is not supported. On some devices, LineageOS will record the microphone instead of the actual call audio. I can check if your ROM is set up that way.

BCR only supports recording call audio (`VOICE_CALL` source). It cannot fall back to using the microphone (`MIC` source).

**Comment by AlirezaSharifi8290** [comment]
> Which device are you using?
J700H
> Can you link to the exact LineageOS ROM?
yes, ofc
https://xdaforums.com/t/rom-13-j7elte-j7xlte-unofficial-lineageos-20-0-alpha.4524889/
j7elte version

**Comment by chenxiaolong** [comment]
Thanks for the link! It looks like my suspicion is correct:

![image](https://github.com/chenxiaolong/BCR/assets/646253/84b495eb-f41d-4a22-90e9-a073a0c70b6b)

1 is the microphone, while 4 is the actual call audio. It looks like your device does not support proper call recording (at least with this ROM) so LineageOS's Dialer uses the microphone instead. Unfortunately, this means you won't be able to use BCR.
