### ISSUE TITLE
[Suggestion] Cloud Saving

### ISSUE THREAD

**Issue by lavoie005** [chenxiaolong/BCR#442]
Hi Chenxiaolong, hope you are doing well.
May i ask you to add a little feature to your apps.
When we save record, if you can add Google Drive path for cloud backup it will be very great.
I explain you the problem i got.
I need to backup my call in a cloud.
I use a third app call FolderSync, 2 problem happen
1. It is not real time sync
2. That drain all my battery, i mean ALL 💩.

I know you want to keep it basic, But i think cloud save it really basic in the 20 century 👌

Thank for your app, all your work it very appreciate.
Have a good one

**Comment by chenxiaolong** [comment]
This is already supported for any cloud provider that supports selecting a directory via the system file picker. Unfortunately, Google Drive and OneDrive don't support this even though Android had the capability since 5.0.

Other apps work around this by directly integrating cloud storage into the app, but I don't plan on doing that for BCR.
