### ISSUE TITLE
Support for Default Call Redirection App

### ISSUE THREAD

**Issue by Xeboc** [chenxiaolong/BCR#443]
When using a call redirecting app such as Google Voice, BCR is using the initially dialed phone number for filenames/metadata and not actual number being called.  Incoming calls work correctly, but all outgoing calls that are redirected have the same incorrect phone number (the proxy phone number).  This redirecting happens when Google Voice is configured:

Making and receiving calls - Use carrier only
Calls started from this device's phone app - Use your Google Voice number

Can support for Call Redirection Apps be added to BCR, so that it saves the number being called, and not the proxy number?

**Comment by chenxiaolong** [comment]
I've added support for this in #443. Unfortunately, due to Android's APIs work, there are several limitations:

* The redirected call must use standard phone calls instead of VOIP. Google Voice works because it uses proxy phone numbers as you've found out. Other redirection services might not work.
* The call must not be a conference call.
* Auto-record rules will not work. Redirected calls will always be treated as `All other calls`.
* During the call, BCR's notification will show the proxy phone number.
* BCR must be granted the call logs permission.

For the last 4 limitations, the reason is that only the dialer app knows the original phone number. The Android telephony system itself is completely unaware of it--it only ever sees the proxy number. BCR can only find the original phone number by searching the call log after the dialer inserts the call log entry at the end of the call.
