### ISSUE TITLE
bcr is displayed after the alpha update

### ISSUE THREAD

**Issue by roseadmin** [chenxiaolong/BCR#470]
bcr is no longer displayed after the alpha update, and even the icon is gone.
The alpha version is 26402.

**Comment by yahorchik1** [comment]
I have same issue. BCR version 1.56, I updated to alpha magisk (kitsune) 26402 
![image](https://github.com/chenxiaolong/BCR/assets/106557393/3c8ff80f-727d-4f70-b989-d93fdd999054)

**Comment by chenxiaolong** [comment]
Sorry, I don't know what is causing this. I can't find the source code to Magisk Alpha--is it open source?

**Comment by yahorchik1** [comment]
@chenxiaolong https://github.com/HuskyDG/magisk-files/releases check here

**Comment by chenxiaolong** [comment]
Thanks. Looks like that is quite different from official Magisk with how it handles mounting things from Magisk modules. There's nothing BCR can do to work around that.

This issue occurs when Android is not able to access BCR's apk (presumably due to some root hiding feature). You'll probably need to play around with the settings to see if it's possible to avoid hiding root from system components.

**Comment by yahorchik1** [comment]
Yes, I checked settings of new magisk (kitsune) 26402, need to give permissions to apps, that need root access. Added BCR in SUList, than start to work.

**Comment by chenxiaolong** [comment]
> Yes, I checked settings of new magisk (kitsune) 26402, need to give permissions to apps, that need root access. Added BCR in SUList, than start to work.

Great! Thanks for reporting back with the solution.
