### ISSUE TITLE
Can't find recordings

### ISSUE THREAD

**Issue by maxonandroid** [chenxiaolong/BCR#472]
I recently had a conversation that I wanted to relisten to. The location of saved recordings was sdcard/Android/data/com.chiller3.bcr/ (I have changed this in the past but occasionally it resets itself)

I am on rooted Pixel 8 Pro. Using Solid Explorer I was unable to find the com.chiller3 folder. So instead I searched with FV manager using Shizuku. I was then able to see but not access the proper folder. (As an aside, after I changed the save location I can no longer see the com.chiller3 folder)

My voice recordings give the success notification when I hang up, so I believe they are (hopefully) somewhere. Since changing the default folder to Downloads and I am now able to find and listen to a recording from today, so I know this is working properly. 

Where and how do I get to my past recordings saved in the com.chiller3 folder 🙏

**Comment by chenxiaolong** [comment]
> I have changed this in the past but occasionally it resets itself

There are two scenarios where this can happen that I'm aware of:

* If the app still shows your custom folder, but the recordings are saved to `/sdcard/Android/data/com.chiller3.bcr`, then Android revoked BCR's access to the custom folder. This is usually caused by other Magisk modules or "root hiding" functionality.
* If the app shows `/sdcard/Android/data/com.chiller3.bcr`, then the settings might have been reset. This can also be caused by "root hiding" functionality, but can also happen if Android boots even a single time without Magisk fully running. In this situation, Android thinks BCR no longer exists, so it wipes the data.

> Where and how do I get to my past recordings saved in the com.chiller3 folder 🙏

The easiest way to access the folder (no root required) is via Android's built in file manager (not to be confused with Google Files). You can access it from Android's Settings -> Storage -> Documents & other. The built in file manager has special permissions that allow it to access `/sdcard/Android/data`.

Normal apps aren't supposed to be able to access `/sdcard/Android/data` due to restrictions added in Android 11. However, the code was buggy, so file managers found a workaround to access the folder anyway. I believe this was in the latest Android 14 build, so it's no longer possible.

**Comment by maxonandroid** [comment]
Thank you for helping me understand more.
Sadly I think some of my recordings are gone forever.

Really appreciate the project!

**Comment by chenxiaolong** [comment]
No problem! Sorry to hear the files are gone.

I wish there was a better default directory BCR could use that's immune to these sorts of issues. Unfortunately, due to Android's restrictions, the `/sdcard/Android/data` folder is the only folder apps are allowed to write to by default that's (kind of) accessible by the user.

**Comment by Shao128** [comment]
I'm putting this here for reference as it may help someone in the future.  BCR showed the folder being used as `/storage/emulated/0/Android/data/com.chiller3.bcr/files` however, even using a root browser I could not find the folder.  After some digging I was able to find all my recording located in (you'll need root): `/data/media/0/Android/data/com.chiller3.bcr/files`

**Comment by maxonandroid** [comment]
Interestingly enough, this was helpful.
Thank you for sharing!
I was able to locate several calls in the folder (path) you listed, within
hours of the main one I was looking for. But for whatever reason the key
recording is gone.

Thank you for the follow up!
Max
