### ISSUE TITLE
Issue Running Project

### ISSUE THREAD

**Issue by pakhranijatin97** [chenxiaolong/BCR#491]
Execution failed for task ':app:processDebugResources'.
> Could not isolate parameters com.android.build.gradle.internal.dependency.AarResourcesCompilerTransform$Parameters_Decorated@5a7d34ed of artifact transform AarResourcesCompilerTransform
   > Could not isolate value com.android.build.gradle.internal.dependency.AarResourcesCompilerTransform$Parameters_Decorated@5a7d34ed of type AarResourcesCompilerTransform.Parameters
      > Dependency verification failed for configuration ':app:detachedConfiguration2'
        One artifact failed verification: aapt2-8.1.3-10154469-osx.jar (com.android.tools.build:aapt2:8.1.3-10154469) from repository Google
        If the artifacts are trustworthy, you will need to update the gradle/verification-metadata.xml file. For more on how to do this, please refer to https://docs.gradle.org/8.4/userguide/dependency_verification.html#sec:troubleshooting-verification in the Gradle documentation.

**Comment by chenxiaolong** [comment]
Ah crap, that gradle behavior is kind of annoying. This is happening because I develop on Linux and when `gradle/verification-metadata.xml` gets generated, it only includes dependencies that are pulled in on Linux systems (which is everything besides `aapt2`, apparently).

I'm not sure how to fix this (if it's even possible with gradle), but there are two workarounds:

* You can run `python gradle/update_verification.py` to redownload and regenerate the checksums and then run `git diff` to confirm that it only added `aapt2-8.1.3-10154469-osx.jar` for macOS and nothing else.

* Or if you don't care about the checksum verification, you can just delete the `gradle/verification-metadata.xml` file.

**Comment by pakhranijatin97** [comment]
Extracted checksum for aapt2-8.1.3-10154469-osx.jar using command "shasum -a 512 filename/path" and added below lines in gradle/verification-metadata.xml on line 721 and project ran as expected : 

<artifact name="aapt2-8.1.3-10154469-osx.jar">
<sha512 value="b47a61ad6d1fa9a5cdd61fbdb2e748219e857b26d548ae422b5f5894db01575cb1f1c33d5a08c8eb8dba50520823ded6d45daf647fe4402848ae73e5c743b83e" origin="Generated by Gradle"/>
</artifact>

**Comment by chenxiaolong** [comment]
This is fixed by #493 and should no longer be a problem with future dependency updates.
