### ISSUE TITLE
Failed to record call

### ISSUE THREAD

**Issue by vunghi021198** [chenxiaolong/BCR#507]
![Screenshot_20240303-135134.png](https://github.com/chenxiaolong/BCR/assets/39901072/5789192e-3de9-49bb-ba3e-8b7868966100)

![Screenshot_20240303-135133.png](https://github.com/chenxiaolong/BCR/assets/39901072/3fcca121-b212-4438-b33d-87368539e31d)

![Screenshot_20240303-135216.png](https://github.com/chenxiaolong/BCR/assets/39901072/500ff973-71dd-4ecd-a5a0-254b3ac0d348)

I've been having this issue on 1.60 only. Same setup as shown in screenshot till 1.59, same ROM, no issue recording. Hope you can look into this. Thank you.

**Comment by chenxiaolong** [comment]
If you change the sample rate to 48 kHz, does it still fail?

**Comment by vunghi021198** [comment]
> If you change the sample rate to 48000 Hz, does it still fail?

Oh my god how silly of me, I dont know since when did it change to 16000, used to be 48000 since 1.40, somehow updating from 1.59 to 1.60 changed the sample rate to 16000. Everything works normally now on 48000. Thank you and sorry for wasting some of your time.

**Comment by chenxiaolong** [comment]
It's not a waste of my time at all :)

1.60 changed the default from 48000 Hz to 16000 Hz. During the update, if you never changed the sample rate in the past, then BCR would use the new default value. It seems that your device doesn't support 16000 Hz for some reason. (If you wouldn't mind posting some additional details, it might help with understanding why--please see my previous edited comment.)

Since 16000 Hz is clearly problematic, I will revert the change and set the default back to 48000 Hz in version 1.62.

**Comment by vunghi021198** [comment]
> It's not a waste of my time at all :)
> 
> 1.60 changed the default from 48000 Hz to 16000 Hz. During the update, if you never changed the sample rate in the past, then BCR would use the new default value. It seems that your device doesn't support 16000 Hz for some reason. (If you wouldn't mind posting some additional details, it might help with understanding why--please see my previous edited comment.)
> 
> Since 16000 Hz is clearly problematic, I will revert the change and set the default back to 48000 Hz in version 1.62.

I'm not sure what kind of additional details I can give, if you mean my device, it's Redmi K20 Pro (raphael)

**Comment by chenxiaolong** [comment]
Thanks! Sorry, by "additional details", I only meant the codec info

**Comment by vunghi021198** [comment]
> Thanks! Sorry, by "additional details", I only meant the codec info

![Screenshot_20240303-145322.png](https://github.com/chenxiaolong/BCR/assets/39901072/1a56a2bd-d45d-4639-998d-92a3c97f317a)

![Screenshot_20240303-145405.png](https://github.com/chenxiaolong/BCR/assets/39901072/d210b505-20c7-4150-a5af-5ee6940112ea)

Here are the two I can find

**Comment by chenxiaolong** [comment]
Thanks! That confirms it then. The device only supports 48000 Hz.

That's incredibly weird though. `c2.android.opus.encoder` is the default Opus encoder shipped in Android. The encoder has supported multiple sample rates in every version of Android since 2018. I guess Redmi must have disabled the other sample rates for some reason.

**Comment by vunghi021198** [comment]
> Thanks! That confirms it then. The device only supports 48000 Hz.
> 
> That's incredibly weird though. `c2.android.opus.encoder` is the default Opus encoder shipped in Android. The encoder has supported multiple sample rates in every version of Android since 2018. I guess Redmi must have disabled the other sample rates for some reason.

This is a Redmi series, more like a flagship killer tier so mostly some of the higher end features will be cutoff to reduce the cost and the selling price.

**Comment by chenxiaolong** [comment]
This will be fixed #508, which changes BCR's behavior so that only the sample rates supported by the device are listed. This will be included in the next version of BCR (version 1.62).

**Comment by thewh1teagle** [comment]
I just had similar issue. I changed opus to m4a and set to 16khz then it recorded.
