### ISSUE TITLE
How to replace "start recording notification sound"? Where is this file places?

### ISSUE THREAD

**Issue by sspphheerraa** [chenxiaolong/BCR#511]
Hello. When call recording started there's short ring playing, that notificate about record starting. I want to replace that sound with another. How can I do that, and where is it places?

**Comment by chenxiaolong** [comment]
Can you explain a bit more about the sound? Are you referring to Android's normal notification sound? (because BCR does not play any of its own sounds)

For Android's notification sound, you can change in from Android's Settings -> Apps -> BCR -> Notifications -> Background services:

![Screenshot_20240308-104217](https://github.com/chenxiaolong/BCR/assets/646253/e8c05da8-a76c-4463-91b1-506604a8b048)

**Comment by sspphheerraa** [comment]
Well, I hear this sound (check attachment) from my phone when conversation is started. However, my interlocutor doesn't hear it (I checked it), and in record that sound is absent too.
Do you hear something like that?
Android 14 (LineageOS 21).

https://github.com/chenxiaolong/BCR/assets/10348818/c6fff63b-f587-4e50-89f2-d742ae47f231

**Comment by chenxiaolong** [comment]
Interesting. I have no idea what that could be. On my device, no sound is played at all.

**Comment by MrKingMichael** [comment]
> Well, I hear this sound (check attachment)

That's the in call notification sound. On my Pixel 5, stock 14 (UP1A.231105.001.B2) build it is located in `/product/media/audio/ui/InCallNotification.ogg` therefore you cannot change it without root. Like chenxiaolong told you, it is possible to mute this notification through your settings so that it does not make any sound when it appears.
