### ISSUE TITLE
Error BCR android 14

### ISSUE THREAD

**Issue by mmm876** [chenxiaolong/BCR#544]
Hello, i get this error 
[crash.log.txt](https://github.com/chenxiaolong/BCR/files/15360930/crash.log.txt)

How can solve ?

**Comment by chenxiaolong** [comment]
The crash is happening because Android can't access BCR's icon when it tries to show a notification. This is usually caused by other modules that try to hide the existence of root. I'd suggest removing those module if you have any.

Some other folks have been able to work around this by extracting the `.apk` from BCR's `.zip` and then installing that normally. It might be worth trying that too.

**Comment by mmm876** [comment]
It work for me. Thanks 
"Some other folks have been able to work around this by extracting the .apk from BCR's .zip and then installing that normally. It might be worth trying that too."
