### ISSUE TITLE
Installed module breaks system biometric features (LineageOS, Android 14, Magisk 27.0)

### ISSUE THREAD

**Issue by NikMAX2077** [chenxiaolong/BCR#547]
**BCR module versions I tried**: 1.62, 1.61, 1.59 and 1.53 (release)
**Device**: Redmi 8 (olive)
**ROM**: LineageOS 21.0-20240502-nightly-Mi439 (Android 14)
**Root**: Magisk 27.0 stable (with Zygisk on)

**Problem**: after installing the module and reboot the system biometric unlock of the phone and applications stopped working. It's looks like no fingerprints were added. Biometric features disappeared from system settings. They are still visible in the search in the settings app, but trying to open them crashes the settings app.

After disabling the module from Magisk and reboot the phone, everything returns to normal and fingerprint features starts working again. Very strange.

UPD4: Everything start working fine after I turned off all other modules. Searching for conflict modules...
UPD5: So I tried to reinstall Magisk and install modules in following sequence (single module per reboot):
1. BCR - everything OK
2. MicroG installer revived - OK
3. Advanced Charging Controller - OK
4. Viper4AndroidFX - problem appears!

Then I turned off Viper module and after reboot problem was gone. So it's look like Viper module make some changes that conflicts with BCR, but it's very strange that this conflict affect system biometric functionality

**Comment by chenxiaolong** [comment]
Interesting! I don't really have any idea why BCR and the Viper module would conflict. Especially right after reboot, since BCR doesn't run in the background until a call is active.

It might be worth trying to grab a logcat right after a reboot, but before logging in the first time. If there's a system component crashing, it'll likely show up in there.

**Comment by NikMAX2077** [comment]
Problem has gone after some LineageOS updates several months ago. So it was ROM bug I think

**Comment by nikmax42** [comment]
Problem appears again now 
- LineageOS 23
- Magisk 29.0, Magisk 30.6
- BCR 1.87

I have only BCR module now. 
When module is enabled, system just "lost" biometric unlock features. Screen turns-on when I touch fingerprint scanner, but device stay locked. I'm also unable to unlock protected apps, because fingerprint unlock dialog doesn't even appears. So it looks like device biometric capabilities doesn't broke entirely, but screen and apps unlocking does.
When module is disabled, biometric unlock "appears" back and works as expected.

I don't have any ideas how, but BCR definitely cause some troubles with biometric components.
