### ISSUE TITLE
Recorded audio changes in volume depending on how loud I have my volume set during the call

### ISSUE THREAD

**Issue by deoxal** [chenxiaolong/BCR#566]
Would it be feasible to merge the uplink and downlink audio sources instead of using the voice communication audio source so putting the caller on speaker doesn't change the recording?

**Comment by chenxiaolong** [comment]
This is something I've tried implementing, but the audio drivers don't support that properly: https://github.com/chenxiaolong/BCR/issues/124#issuecomment-1229254496. Unfortunately, there's not really anything I can do to work around this behavior.

**Comment by chenxiaolong** [comment]
With #772, which will be included in version 2.0, BCR can now optionally record in stereo for devices that support it. The uplink is recorded to the left channel and the downlink to the right channel. Currently, only newer Google Pixel devices are known to support this.

The recorded volume is likely still tied to what the volume was during the call, since that's just part of the audio provided by Android, but with a stereo recording, it should hopefully be easier to edit the audio with a tool like Audacity if needed.
