### ISSUE TITLE
[Question] call recording announcement - all / both parties

### ISSUE THREAD

**Issue by ElsAr4e** [chenxiaolong/BCR#568]
If you use Google Dialer (on non-rooted phones) there will be a call recording announcement that the call is now being recorded: https://www.youtube.com/watch?v=PBzsg6yDUkM

This notification will be played on both phones - the person who is called and the caller? -You might be able to disable that: https://beebom.com/how-disable-call-recording-announcements-android-realme-oppo-vivo-iqoo-xiaomi-oneplus/

However: What happens if you use BCR on rooted phones
together with

- a default dialer that is NOT the Google Dialer (like Samsung Phone)
- the default dialer - Google Dialer
- a third-party calling app (like Fossify Phone App (https://github.com/FossifyOrg/Phone))

Will there be a call recording announcement even if you use BCR and NOT the native call recording?
Can you be sure that the other party/parties will never get a notification that the call is now being recorded?

Does it also depend which default dialer the other person uses?

**Comment by chenxiaolong** [comment]
The announcement is something the default/system dialer does. It sends the announcement audio to the call audio stream when using the built-in recording feature. Google Dialer implements this and I would imagine Samsung's dialer does too.

Third party dialers will never send an announcement for the same reason that they can't record calls themselves. It requires system app permissions.

BCR never outputs any audio to the call audio stream.

> Will there be a call recording announcement even if you use BCR and NOT the native call recording?

I'm not aware of any dialer that tries to detect third party recorders and send the audio. It's theoretically possible though.

> Can you be sure that the other party/parties will never get a notification that the call is now being recorded?

No, there's no way to guarantee this. AOSP (and the stock OS on Pixel devices) works as I described above, where the system dialer is responsible for sending the announcement audio. There's nothing that prevents OEMs from implementing this at the OS-level instead of at the dialer-level though.

> Does it also depend which default dialer the other person uses?

No, what the other person uses doesn't matter at all. It's your local device that's sending the audio.

**Comment by ElsAr4e** [comment]
Thanks for your answers!

> Google Dialer implements this and I would imagine Samsung's dialer does too.

I am using Galaxy Tab A7 Lite (no root) and - until now (and on the devices I've testest) Samsung does NOT have any call recording announcement - same when it comes to Mate 20 Pro -both (no root) with native call recording (tested with all parties).

This might change in the future but I've never read this is planned?

When it comes to record emergency calls using BCR: If BCR is used to record emergency calls even if I use now Google Dialer there still should be no call recording announcement (since I don't usebuilt-in recording feature) ?

**Comment by chenxiaolong** [comment]
No problem!

> I am using Galaxy Tab A7 Lite (no root) and - until now (and on the devices I've testest) Samsung does NOT have any call recording announcement - same when it comes to Mate 20 Pro -both (no root) with native call recording (tested with all parties).
>
> This might change in the future but I've never read this is planned?

That's good to know. With Google and Apple (in the upcoming iOS version) both sending a call recording announcement, I'm guessing Samsung/etc will eventually do the same (but that's a total guess).

> When it comes to record emergency calls using BCR: If BCR is used to record emergency calls even if I use now Google Dialer there still should be no call recording announcement (since I don't use the built-in recording feature) ?

That's correct.

**Comment by ElsAr4e** [comment]
Maybe you should add these informations that there won't be a (known) call recording announcement if you use BCR (only - so no native call recording used) to record a call like in the installation instructions and/or the docs? (Like https://github.com/chenxiaolong/BCR/issues/524#issuecomment-2038428005)

Because I think it would be useful,

**Comment by chenxiaolong** [comment]
Good idea. Added in 6e6a08b073ef01e02833510cf0af6386b637f4be

**Comment by ElsAr4e** [comment]
@chenxiaolong I've been looking at the commit and I think you should add something like (after "BCR does not announce ..."): "Keep in mind if you (also/ still) use the built-in call recording at the same time and/or instead of BCR it could be possible that there will be a call recording announcement"

And something like "As mentioned ["list the reference"] you should only use one call recorder at the same time (in that case just BCR?)"
