### ISSUE TITLE
Error when recording "silent"

### ISSUE THREAD

**Issue by immerzu** [chenxiaolong/BCR#579]
"The recording was discarded bacause the audio was completely silent. This device might..."

I don't find this message useful because I know I hung up before the person I was calling was able to take the call. Can this error message be switched off?

Thank you.

**Comment by chenxiaolong** [comment]
This notification is currently in the "failure alerts" notification channel in Android's settings, so there's no way to turn it off without also hiding other errors. I can split it out to a separate notification channel in the next release.

(That notification was added because I've gotten too many bug reports from folks with devices that don't properly support call recording.)

**Comment by chenxiaolong** [comment]
This has been implemented in #583. In the next version of BCR, you'll be able to disable this notification from Android's Settings -> Apps -> BCR -> Notifications -> Disable "Pure silence warnings".

In the meantime, feel free to use this test build if you'd like the functionality right away: [BCR-1.69.r5.gcf2526b-release.zip](https://github.com/user-attachments/files/16571101/BCR-1.69.r5.gcf2526b-release.zip)
