### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by Shidapu** [chenxiaolong/BCR#586]
App crashing. Got some logs. 
Found the issue to be :[https://github.com/snake-4/Zygisk-Assistant](url)? 

Possible fix to make it work with Zygisk Assistant? 

[crash.log (1).txt](https://github.com/user-attachments/files/16660148/crash.log.1.txt)
[crash.log (2).txt](https://github.com/user-attachments/files/16660150/crash.log.2.txt)
[crash.log.txt](https://github.com/user-attachments/files/16660151/crash.log.txt)

**Comment by chenxiaolong** [comment]
I don't know what Zygisk Assistant does, but if it's hiding or unmounting BCR's files, it will definitely break things. The crash you're seeing is caused by some Android component not being able to access BCR's APK.

You might be able to work around this by extracting the APK from BCR's module zip and installing it. I'd recommend not using any root hiding modules though.

**Comment by Shidapu** [comment]
Just for info if someone needs the solution in the future, install BCR with module. Right after, extract the apk from the module zip file and update the BCR application with the extracted apk file.

**Comment by NikunjKhangwal** [comment]
> Just for info if someone needs the solution in the future, install BCR with module. Right after, extract the apk from the module zip file and update the BCR application with the extracted apk file.

Thanks a lot
