### ISSUE TITLE
Crash after beginning of call

### ISSUE THREAD

**Issue by hcosserat** [chenxiaolong/BCR#592]
Hi ! 
First of all, thanks of all your work, really love BCR.

However it stopped working recently and I don't know why.

My device is a Pixel 6a running Android 14 update of August, rooted with Magisk 27007. BCR version is 1.69.

Here are the logs of last recording : 

[log.txt](https://github.com/user-attachments/files/16829721/log.txt)

Thanks in advance

**Comment by chenxiaolong** [comment]
Glad you like BCR!

Which other Magisk modules do you have installed? Is there anything for hiding root?

This happens when something prevents Android from accessing BCR's icon when displaying a notification. This is frequently caused by some root hiding module making BCR's `.apk` inaccessible to some part of the system.

If you're not able to find what's causing this (or if it's caused by another module that you don't want to uninstall), you might be able to work around it by extracting the `.apk` from BCR's module zip file and installing it.

**Comment by hcosserat** [comment]
Thanks for your answer !

Yes, I am using Shamiko, that's probably it. I used the workaround you gave and everything works fine now.

Thank you :)
