### ISSUE TITLE
BCR will NOT start (Android 11, RUI 2.0)

### ISSUE THREAD

**Issue by kojinmalia** [chenxiaolong/BCR#608]
I'm on a Realme X50 Pro using RUI2.0 system (A11 > i do not which to move to their A12 version, but did try it and strangely there BCR works!); Here's what happens: I install last version with last magisk. I tap on the app icon : after a delay of 5-6sec, i see a black screen (with status bar color changing) and it hangs there. I never get the superSU root request or anything, it just stays there. Please let me know if/how should i provide more info.

**Comment by chenxiaolong** [comment]
Please grab a logcat immediately after the crash occurs and upload that. I'm not sure why it would crash on startup. (If you have any root hiding modules installed, I'd suggest temporarily disabling those to see if they are the cause.)

It's normal that there's no root prompt because BCR doesn't require root. It only requires system app permissions, which it already got by installing as a Magisk module.
