### ISSUE TITLE
Receive error saying "No Audio" when using the LineageOS Phone app, works fine under Google Phone app

### ISSUE THREAD

**Issue by macmanjimmy** [chenxiaolong/BCR#609]
Receive an error saying "No Audio" when using the LineageOS Phone app, works fine under the Google Phone app

Need to use LineageOS Phone app, due to issues with 911 calls

Attached is a screenshot of the error message

Current Version LineageOS 20241005 current version BCS 1.71

Thanks
![Screenshot_20241007-154746_Nova Launcher](https://github.com/user-attachments/assets/d79e55e7-833a-4273-bd8d-d0aec4160415)

**Comment by chenxiaolong** [comment]
Sorry, there's nothing that BCR can do about this unfortunately. Android controls if audio gets sent to BCR or not.

However, since you mentioned LineageOS, it's worth double checking to make sure LineageOS dialer's builtin call recorder is disabled. Android does not allow two apps to record calls at the same time.

**Comment by macmanjimmy** [comment]
LineageOS Call recorder is not available here in the US, why I'm using this.. can use Google Phone unless I need to call 911, which isn't too often, knock wood
