### ISSUE TITLE
BCR Crash and Missing Icon Display

### ISSUE THREAD

**Issue by AresAht** [chenxiaolong/BCR#616]
The app crashes whenever a call recording is attempted. Additionally, the app doesn't display the classic BCR icon, but instead shows the generic Android icon, similar to how Magisk behaves when the app is hidden. You can find the logs attached below.
[crashlog.txt](https://github.com/user-attachments/files/17424250/crashlog.txt)

**Comment by chenxiaolong** [comment]
Thanks for the logs. It unfortunately didn't capture the crash, but based on what you're describing (generic Android icon), I'm pretty sure I know what the issue is.

Do you have any root hiding modules installed, like Shamiko? Those modules frequently cause issues with BCR because it prevents Android itself from accessing BCR's apk, which is why the icon is generic. Crashes usually occur when BCR tries to show a notification and Android can't load the notification icon from the apk.

Many people have been able to work around the problem by extracting BCR's apk from the module and then installing it normally. I'd suggest giving that a try.

**Comment by AresAht** [comment]
> Many people have been able to work around the problem by extracting BCR's apk from the module and then installing it normally. I'd suggest giving that a try.

It works perfectly. Thanks a lot !
