### ISSUE TITLE
white screen

### ISSUE THREAD

**Issue by vorach** [chenxiaolong/BCR#63]
I test BCR on oneplus 10 pro last Europe update Android 12
I have a white screen when i start apps.

I use magisk for installation and 1.9 version

**Comment by chenxiaolong** [comment]
I'd suggest taking a look at the thread at #8. Other folks seem to have fixed the problem by disabling some Magisk or LSPosed modules.

I don't know why this happens on OnePlus devices. The white/gray screen is from the Android system. When this issue occurs, BCR doesn't even begin to load. Because of that, there's nothing I can do to try to workaround the problem.
