### ISSUE TITLE
What happened?

### ISSUE THREAD

**Issue by joimjnbg** [chenxiaolong/BCR#633]
![Screenshot_20241116-161812_KernelSU](https://github.com/user-attachments/assets/2ee6250a-5e05-427b-8fcc-34a1d3dffeb6)
![Screenshot_20241116-161807_Paranoid_Launcher](https://github.com/user-attachments/assets/939538b6-cb84-4538-bd8c-88d731420db3)
How should I do?

**Comment by chenxiaolong** [comment]
This is likely caused by root hiding modules (eg. Shamiko), which prevent certain Android components from accessing BCR's apk (which is why the name and icon are not available). You can try extracting BCR's apk from the module's zip file and installing that. If it doesn't work, you'll have to remove any root hiding modules that might be installed.

**Comment by joimjnbg** [comment]
Thank u sooooo much.it work.
