### ISSUE TITLE
Bad notification(tag=null, id=35) posted from package

### ISSUE THREAD

**Issue by SebastianWojciechowski** [chenxiaolong/BCR#639]
Hi, 
I just installed BCR latest on my new Pixel 9 Pro. I have the latest december A15 feature drop.
Using magisk 28001.

When I start call a call after a sexond i get error dialog saying that bcr crashed and the error file is created instead of a recording.

21333 21333 E RecorderApplication: android.app.RemoteServiceException$BadForegroundServiceNotificationException: Bad notification(tag=null, id=35) posted from package com.chiller3.bcr, crashing app(uid=10287, pid=21333): Couldn't create icon StatusBarIcon(icon=Icon(typ=RESOURCE pkg=com.chiller3.bcr id=0x7f070093) visible user=0 )
12-10 14:12:27.701 21333 21333 E RecorderApplication: 	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2275)
12-10 14:12:27.701 21333 21333

More here
https://pastebin.com/RwXWgrMY

**Comment by chenxiaolong** [comment]
Thanks for the logs. Do you have any root hiding Magisk modules installed? This is caused by something blocking Android from accessing BCR's apk (which is why the error mentions a bad notification icon).

If you have those sorts of modules installed, you'll need to disable them or whitelist BCR in that's possible. Alternatively, you can also extract BCR's apk from the module zip file and install it to work around the problem.

**Comment by SebastianWojciechowski** [comment]
I do have root-hiding modules like Zygisk Assistant, Tricky Store, Shamiko, Play Integrity Fix, etc. 
What worked was extracting the APK from the module ZIP file, as you suggested, and "updating" the BCR APK. 
Now it works, and I have a nice green icon with the BCR text instead of the "chill.." something. Thanks!
