### ISSUE TITLE
Ability to send voice from an audio file instead of microphone and record

### ISSUE THREAD

**Issue by modiamir** [chenxiaolong/BCR#94]
Hello,
Thanks for your effort behind this app. It is a lovely app ❤️ .
I am unsure if this place is relevant to asking my question or not. I need to send a voice from another source than the phone's microphone, like an audio file. Is it possible to do that with a rooted android? or does it need modifying the android kernel?

**Comment by chenxiaolong** [comment]
I was curious too, so I played around for a bit and now BCP is a thing: https://github.com/chenxiaolong/BCP :slightly_smiling_face:  It's just a tech demo, so I don't plan on making many changes to it. Like BCR, it's open source (GPLv3 licensed).

It should work on devices that support the telephony audio output device. Newer Google Pixels support it due to Google Dialer's call screening feature, but I don't know if any other devices do. It very likely requires support from both the kernel and the modem firmware. In general, it's less likely to work than call recording.

Similar to BCR, root is not strictly required--it's just necessary to be a system app. This can be done via a Magisk module or by baking it into the ROM.
