### ISSUE TITLE
File output looks more complex (no real "basic")

### ISSUE THREAD

**Issue by laltroweb** [chenxiaolong/BCR#95]
Sorry bro, i really appreciate this app (now also file retention, so good!) but file output looks very complex atm.
Also, by default is 48khz but if not in error only some pro pixel support this (so, unuseful for most others device).
Imho, can be simply optimized with 3 quality levels: low, medium, full. No more, no less 😅
![Screenshot_20220621-180706_BCR](https://user-images.githubusercontent.com/16841896/174847530-cfffcb7f-14bc-415a-a158-1fc4f6e8b0a3.png)

**Comment by lbdroid** [comment]
Basic vs. Complex.... from the perspective of software complexity? Or from the perspective of ease of use? They are not the same thing. Often to make things simple to the USER requires substantial software complexity.

And guess what? Increased software complexity means increased frequency of bugs and other defects, which really should be avoided.

What you are looking at here, is a focus on basic from the point of view of the SOFTWARE complexity.

What you propose would actually add a lot of complexity to the software, because it would require a separate mapping from low/medium/high to bitrate for each format and sample rate. Instead, there is a nice simple to implement choice in each category. Pick what makes the most sense to you and be done.

However, I would definitely agree that 48 kHz is a bit much for a default setting. Telephone audio runs at 8 or 16 kHz, so having the sample rate default to 16 kHz would be most reasonable.

**Comment by chenxiaolong** [comment]
I'd be open to representing the options a different way if it makes sense, but I don't plan on removing some of the sample rates completely.

> However, I would definitely agree that 48 kHz is a bit much for a default setting. Telephone audio runs at 8 or 16 kHz, so having the sample rate default to 16 kHz would be most reasonable.

This is true, but unfortunately 48 kHz is the most compatible setting because some ROMs either have a broken downsampler or it accepts the lower sample rate and just crashes. Even though the call audio over the wire is 8 or 16 kHz, every Android device I've encountered so far reports the native sample rate as 48 kHz for the `VOICE_CALL` audio stream (the modem might be internally doing some upsampling).
