### ISSUE TITLE
App crashing upon trying to change the output directory

### ISSUE THREAD

**Issue by cranky-pythonista** [chenxiaolong/BCR#99]
I'm on latest v.1.15,,, earlier when I was somwhere around 1.10(can't remember the exact version) I was able to change the output directory normally. Now the app closes instantly. I'm on android 11. Btw I've been using this app since a long time, it worked really fine. Please guide.

**Comment by chenxiaolong** [comment]
Crashes when changing the output directory usually happen if the `DocumentsUI` system app is disabled, modified, or removed. Any chance you're using the MiXplorer Magisk module? Somebody else ran into a similar crash due to that module: https://github.com/chenxiaolong/BCR/issues/86#issuecomment-1163343328

If not, can you grab a logcat after the crash occurs?

**Comment by chenxiaolong** [comment]
Hmm, I'm not sure--I don't use that module myself. You might need to disable that module, pick an output directory in BCR, and then reenable it.
